### ISSUE TITLE
下载新主题后Hexo g 报错

### ISSUE THREAD

**Issue by shujucn** [iTimeTraveler/hexo-theme-hiero#24]
FATAL Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at /Users/shuju/blog/node_modules/hexo/lib/hexo/load_config.js:35:28
    at tryCatcher (/Users/shuju/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/shuju/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/shuju/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/shuju/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/shuju/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/shuju/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/shuju/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/shuju/blog/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by shujucn** [comment]
已解决：不要把 url: http://yoursite.com/ 中url:后面的部分删掉，删掉之后就会报错
